import type { CsQuestionEnglishRegistry } from './csQuestionCopyTypes';
export const CS_QUESTION_COPY_UNIT_5: CsQuestionEnglishRegistry = {
    'cs-q-501': { question: 'After receiving a client SYN in the TCP three-way handshake, what does the server send?', options: ['Only an ACK, followed immediately by application data', 'A SYN-ACK that acknowledges the client sequence number and advertises the server initial sequence number', 'A FIN that terminates the unverified request', 'An RST that resets the endpoint'], solution: [
            "Track both sequence-number spaces: the client must be acknowledged and the server must synchronize its own sequence.",
            "A SYN-ACK that acknowledges the client sequence number and advertises the server initial sequence number",
            "The second handshake message is SYN-ACK, combining acknowledgment of the client with synchronization of the server sequence."
        ], explanation: 'The server cannot reply with a bare ACK because TCP must establish two independent sequence spaces; the SYN introduces the server sequence number while the ACK covers the client SYN.', tags: ['Computer networks', 'TCP/IP', 'Three-way handshake'] },
    'cs-q-502': { question: 'Which statement correctly compares TCP and UDP?', options: ['UDP implements a sliding window for reliable end-to-end flow control.', 'TCP uses connection setup, acknowledgments, retransmission, and congestion control; UDP avoids handshake overhead and suits low-latency voice, games, and DNS.', 'TCP has an 8-byte header while UDP has a 20-byte header.', 'UDP must receive a SYN response before sending data.'], solution: [
            "Separate reliable ordered byte-stream services from connectionless datagrams.",
            "TCP uses connection setup, acknowledgments, retransmission, and congestion control; UDP avoids handshake overhead and suits low-latency voice, games, and DNS.",
            "TCP supplies reliable flow-controlled delivery; UDP supplies lightweight datagrams without handshake or retransmission guarantees."
        ], explanation: 'Low UDP overhead is not a latency guarantee and does not make loss harmless; real-time applications often add their own sequencing, concealment, or selective recovery.', tags: ['Transport layer', 'TCP', 'UDP', 'Network protocols'] },
    'cs-q-503': { question: 'A 100 Mbps CSMA/CD Ethernet has maximum one-way propagation delay $\\tau=2.56\\,\\mu\\text{s}$. What minimum frame length ensures a collision returns before transmission ends?', options: ['256 bits (32 Bytes)', '512 bits (64 Bytes)', '1024 bits (128 Bytes)', '128 bits (16 Bytes)'], solution: [
            "Use $L_{\\min}=2\\tau\\times\\text{Bandwidth}$.",
            "512 bits (64 Bytes)",
            "$2\\times2.56\\,\\mu\\text{s}\\times100\\text{ Mbps}=512$ bits, or 64 Bytes."
        ], explanation: 'Using the one-way delay gives the tempting 256-bit distractor; collision detection must cover the round trip $2\\tau$, and the bandwidth product is in bits before conversion to Bytes.', tags: ['CSMA/CD', 'Ethernet', 'Minimum frame size', 'Collision detection'] },
    'cs-q-504': { question: 'How does BGP-4 Path-Vector routing prevent a loop between autonomous systems?', options: ['It drops every packet after one router hop.', 'A route advertisement carries AS_PATH; a router rejects the route if its own AS number already appears in that path.', 'It limits hop count to 15.', 'Every Internet router floods a global link-state advertisement every 30 seconds.'], solution: [
            "Inspect the advertised AS sequence before accepting the route.",
            "A route advertisement carries AS_PATH; a router rejects the route if its own AS number already appears in that path.",
            "An AS rejects any BGP path containing its own number, preventing interdomain routing loops."
        ], explanation: 'Do not apply RIP’s hop-count rule or an IP TTL to this control-plane problem: BGP detects an AS-level loop by inspecting route ancestry before installing the route.', tags: ['Computer networks', 'BGP', 'AS_PATH', 'Routing protocol', 'Loop prevention'] },
    'cs-q-505': { question: 'What does TCP Reno do after receiving three duplicate ACKs?', options: ['Reset cwnd to one MSS and restart slow start.', 'Send RST and close the connection.', 'Fast-retransmit the missing segment, halve ssthresh, and enter fast recovery because isolated loss is inferred.', 'Set RTO to 60 seconds without retransmitting.'], solution: [
            "Distinguish duplicate-ACK loss evidence from a retransmission timeout.",
            "Fast-retransmit the missing segment, halve ssthresh, and enter fast recovery because isolated loss is inferred.",
            "Three duplicate ACKs trigger fast retransmit and fast recovery without collapsing cwnd to one MSS."
        ], explanation: 'Three duplicate ACKs imply that later segments are still arriving, so Reno treats the loss as isolated; collapsing `cwnd` to one MSS belongs to the more severe timeout path.', tags: ['TCP', 'Congestion control', 'Fast retransmit', 'Fast recovery'] },
    'cs-q-506': { question: 'How does NAPT/PAT let many private hosts share one public IP simultaneously?', options: ['Every device receives one millisecond of Internet access in turn.', 'The router tracks sessions in a NAT table, rewrites each outbound source IP and transport port, and uses the translated port to demultiplex returning traffic.', 'All data is encrypted and sent over a telephone line.', 'The ISP supplies 65,536 public IP addresses for free.'], solution: [
            "Identify the full flow tuple before and after the router rewrite.",
            "The router tracks sessions in a NAT table, rewrites each outbound source IP and transport port, and uses the translated port to demultiplex returning traffic.",
            "NAPT multiplexes many private sessions by assigning distinct 16-bit TCP or UDP port mappings on one public address."
        ], explanation: 'Rewriting only the source IP would leave simultaneous private flows ambiguous; the translated transport port is the discriminator that lets the router reverse the mapping.', tags: ['Computer networks', 'NAT', 'NAPT', 'Port mapping', 'Address translation'] },
    'cs-q-507': { question: 'Which DNS query modes are normally used between a client and local resolver, and between that resolver and hierarchical DNS servers?', options: ['Client broadcast followed by resolver multicast', 'The client requests a recursive final answer; the resolver follows iterative referrals from root to TLD to authoritative server.', 'Both are iterative and the user contacts root administrators.', 'No packets are used because every record is in the boot sector.'], solution: [
            "Determine who is responsible for following referrals to the final authoritative answer.",
            "The client requests a recursive final answer; the resolver follows iterative referrals from root to TLD to authoritative server.",
            "The stub asks its local resolver recursively, while the resolver normally performs iterative queries through the hierarchy."
        ], explanation: 'Recursive versus iterative names who must chase the next referral, not whether the packet uses TCP or UDP; the stub normally delegates that work instead of contacting root servers itself.', tags: ['Computer networks', 'DNS', 'Recursive query', 'Iterative query', 'Domain names'] },
    'cs-q-508': { question: 'What major latency and security improvements does TLS 1.3 provide over TLS 1.2?', options: ['It abandons encryption and sends plaintext.', 'It places Diffie-Hellman key shares in ClientHello/ServerHello for a 1-RTT handshake, permits PSK-based 0-RTT resumption, and removes static RSA key exchange to require forward secrecy.', 'It permits only 56-bit DES.', 'An administrator must issue a paper certificate for every connection.'], solution: [
            "Count handshake round trips and identify whether the key exchange provides forward secrecy.",
            "It places Diffie-Hellman key shares in ClientHello/ServerHello for a 1-RTT handshake, permits PSK-based 0-RTT resumption, and removes static RSA key exchange to require forward secrecy.",
            "TLS 1.3 reduces a normal handshake to 1 RTT, supports 0-RTT resumption, and removes obsolete non-forward-secret choices."
        ], explanation: 'Do not treat 0-RTT as the normal full handshake or as equally safe: it is resumption-only early data and can be replayed, so applications must restrict what it carries.', tags: ['Computer networks', 'Network security', 'TLS 1.3', 'Handshake', 'PFS', '1-RTT'] },
    'cs-q-509': { question: 'For RSA with $p=61$, $q=53$, $n=3233$, and public exponent $e=17$, which equation must private exponent $d$ satisfy?', options: ['$d=n-e=3216$', '$ed\\equiv1\\pmod{\\phi(n)}$, where $\\phi(n)=60\\times52=3120$ and $d=2753$', '$d=e^2\\pmod n=289$', '$d=p+q=114$'], solution: [
            "Compute $n=pq=3233$.",
            "Compute $\\phi(n)=(p-1)(q-1)=60\\times52=3120$.",
            "Use the extended Euclidean algorithm to solve $17d\\equiv1\\pmod{3120}$.",
            "The modular inverse is $d=2753$."
        ], explanation: 'The inverse is taken modulo $\\phi(n)$, not modulo $n$, and ordinary division cannot find it; confusing those moduli produces a value that will not undo RSA exponentiation.', tags: ['Cryptography', 'RSA', 'Euler totient', 'Modular inverse', 'Public-key encryption'] },
    'cs-q-510': { question: 'What transport breakthrough does HTTP/3 over QUIC provide compared with HTTP/2 over TCP?', options: ['Independent stream acknowledgment and recovery mean loss blocks only the affected stream; connection IDs also permit migration between networks.', 'It removes encryption for tenfold speed.', 'Every packet must be one byte.', 'It can transport audio but not HTML.'], solution: [
            "Compare TCP connection-wide ordering with QUIC stream-level delivery state.",
            "Independent stream acknowledgment and recovery mean loss blocks only the affected stream; connection IDs also permit migration between networks.",
            "QUIC removes cross-stream transport head-of-line blocking and supports connection migration."
        ], explanation: 'QUIC does not make loss irrelevant: missing data still blocks its own stream, but unlike TCP it need not hold up unrelated streams that already have complete data.', tags: ['Computer networks', 'HTTP/3', 'QUIC', 'UDP', 'Head-of-line blocking'] },
    'cs-q-511': { question: 'Why does interdomain BGP use a path-vector design rather than a link-state or simple distance-vector design?', options: ['AS_PATH records the complete AS sequence for loop detection and also supports policy routing based on business relationships.', 'BGP works only inside a LAN.', 'Every router must share one root password.', 'BGP carries email text instead of IP routes.'], solution: [
            "Check whether an advertisement exposes both route ancestry and policy attributes across administrative domains.",
            "AS_PATH records the complete AS sequence for loop detection and also supports policy routing based on business relationships.",
            "AS_PATH provides native loop detection and allows each autonomous system to enforce independent routing policy."
        ], explanation: 'BGP is not trying to compute one globally shortest path; autonomous systems may reject or prefer an otherwise reachable path because commercial policy is part of interdomain routing.', tags: ['Computer networks', 'BGP', 'AS_PATH', 'Path vector', 'Autonomous system', 'RPKI'] },
    'cs-q-512': { question: 'What architecture change defines Software-Defined Networking (SDN)?', options: ['It separates route/control decisions from high-speed packet forwarding, centralizes programmable control, and installs flow tables through a southbound interface such as OpenFlow.', 'It removes every network cable and uses infrared remotes.', 'A person stamps every packet before transmission.', 'It limits all links to 56 kbps.'], solution: [
            "Separate the control plane that computes policy from the data plane that executes forwarding rules.",
            "It separates route/control decisions from high-speed packet forwarding, centralizes programmable control, and installs flow tables through a southbound interface such as OpenFlow.",
            "SDN makes network control programmable and logically centralized while switches retain fast data-plane forwarding."
        ], explanation: '“Logically centralized” does not require one physical controller or move packet forwarding into the controller; switches still execute distributed data-plane rules at line rate.', tags: ['Computer networks', 'SDN', 'OpenFlow', 'Control plane', 'Data plane', 'Traffic engineering'] },
    'cs-q-513': { question: 'How does Google BBR differ from loss-based congestion control such as Reno or CUBIC?', options: ['BBR models bottleneck bandwidth and minimum propagation RTT, pacing near the bandwidth-delay product instead of filling queues until loss.', 'It stops sending packets entirely.', 'It delegates every packet to DNS.', 'It forces every user to share one IP address.'], solution: [
            "Estimate $\\text{BDP}=\\text{BtlBw}\\times\\text{RTprop}$ and compare inflight data with that path model.",
            "BBR models bottleneck bandwidth and minimum propagation RTT, pacing near the bandwidth-delay product instead of filling queues until loss.",
            "BBR targets full bottleneck utilization with short queues, reducing bufferbloat rather than using loss as the primary signal."
        ], explanation: 'BBR’s model is not a promise of zero loss or fixed rate: it must continually probe bandwidth and minimum RTT, and a wrong estimate can still build queues or compete unfairly.', tags: ['Computer networks', 'TCP', 'Congestion control', 'BBR', 'CUBIC', 'Bufferbloat', 'BDP'] },
    'cs-q-514': { question: 'What are the key handshake and cryptographic changes in TLS 1.3 (RFC 8446)?', options: ['A full handshake takes 1 RTT with a ClientHello key share; resumption may carry replay-sensitive 0-RTT early data; static RSA and CBC suites are removed in favor of forward-secret (EC)DHE.', 'Certificate validation is removed.', 'Every symmetric cipher becomes a Caesar cipher.', 'A page may load only once before re-signing.'], solution: [
            "Compare round trips, permitted key exchange, and legacy cipher-suite removal.",
            "A full handshake takes 1 RTT with a ClientHello key share; resumption may carry replay-sensitive 0-RTT early data; static RSA and CBC suites are removed in favor of forward-secret (EC)DHE.",
            "TLS 1.3 reduces latency while requiring modern authenticated encryption and forward-secret key agreement."
        ], explanation: 'The 0-RTT option is easy to over-credit: it applies only to PSK resumption and its early data is replayable; the ordinary forward-secret handshake still takes 1 RTT.', tags: ['Computer networks', 'TLS 1.3', 'HTTPS', 'Cryptography', '0-RTT', 'ECDHE', 'Forward secrecy'] },
    'cs-q-515': { question: 'How does DNSSEC defend against forged DNS cache entries?', options: ['Each zone signs RRsets with RRSIG; parent DS records authenticate child keys up to a root trust anchor, allowing a resolver to verify origin and integrity.', 'Every domain name is replaced with Morse code.', 'Users visit a data center for every lookup.', 'Every DNS server is disconnected from the Internet.'], solution: [
            "Follow the signature chain from the answer zone through DS delegations to the configured trust anchor.",
            "Each zone signs RRsets with RRSIG; parent DS records authenticate child keys up to a root trust anchor, allowing a resolver to verify origin and integrity.",
            "DNSSEC detects forged records with asymmetric signatures and a hierarchical chain of trust."
        ], explanation: 'DNSSEC authenticates origin and integrity; it neither encrypts the queried name nor hides the answer, so it should not be confused with DNS privacy mechanisms such as DoH or DoT.', tags: ['Computer networks', 'DNSSEC', 'Cache poisoning', 'Kaminsky attack', 'Digital signatures', 'Chain of trust'] },
    'cs-q-516': { question: 'How does QUIC (RFC 9000) remove HTTP/2 transport head-of-line blocking and support mobility?', options: ['User-space QUIC over UDP gives each stream independent ordering and recovery, so one loss stalls only that stream; a 64-bit Connection ID preserves the connection across Wi-Fi and 5G changes.', 'Every QUIC connection closes after one second.', 'Packets are sent as email attachments.', 'Acknowledgments are removed and lost data is ignored.'], solution: [
            "Track loss recovery per stream and identify the connection independently of an IP-address tuple.",
            "User-space QUIC over UDP gives each stream independent ordering and recovery, so one loss stalls only that stream; a 64-bit Connection ID preserves the connection across Wi-Fi and 5G changes.",
            "Independent QUIC streams avoid connection-wide HoL blocking, and Connection IDs enable migration between network paths."
        ], explanation: 'Running over UDP does not make QUIC unreliable: QUIC supplies its own acknowledgments and recovery, while the Connection ID—not the UDP 4-tuple—lets the endpoint survive an address change.', tags: ['Computer networks', 'QUIC', 'HTTP/3', 'Head-of-line blocking', 'UDP', 'Connection migration', 'Connection ID'] },
};
