import type { CsQuestionEnglishRegistry } from './csQuestionCopyTypes';
export const CS_QUESTION_COPY_UNIT_4: CsQuestionEnglishRegistry = {
    'cs-q-401': { question: 'Which item is not one of the four Coffman conditions required for deadlock?', options: ['Mutual exclusion', 'No preemption', 'Dynamic priority inversion', 'Circular wait'], solution: [
            "Recall mutual exclusion, hold and wait, no preemption, and circular wait.",
            "Priority inversion is a scheduling hazard, not a necessary condition for deadlock."
        ], explanation: 'Do not mistake a scheduling symptom for a Coffman prerequisite: priority inversion can delay a task without creating circular resource ownership.', tags: ['Operating systems', 'Deadlock', 'Process synchronization'] },
    'cs-q-402': { question: "Which page-replacement algorithm can never exhibit Belady's anomaly as the number of frames increases?", options: ['FIFO', 'Least Recently Used (LRU)', 'Random replacement', 'Second-Chance FIFO'], solution: [
            "Choose a stack algorithm whose pages with n frames are always a subset of those with n+1 frames.",
            "Least Recently Used (LRU)",
            "LRU has the stack property, so adding frames cannot increase its page-fault count."
        ], explanation: "The trap is to group every recency-based policy together: only a stack property guarantees that the smaller frame set is nested inside the larger one; Second-Chance FIFO lacks that guarantee.", tags: ['Virtual memory', 'LRU', "Belady's anomaly", 'Page replacement'] },
    'cs-q-403': { question: "What does it mean for a resource-allocation state to be safe under the Banker's algorithm?", options: ['No process is waiting and utilization is exactly 100%.', 'At least one safe process sequence exists in which every process can obtain its maximum remaining need and finish.', 'Deadlock has already occurred but automatic restart is possible.', 'Every process is Ready and no lock is needed.'], solution: [
            "Search for an ordering in which Available resources satisfy each next process Need after earlier processes release their allocations.",
            "At least one safe process sequence exists in which every process can obtain its maximum remaining need and finish.",
            "A safe state contains at least one completion sequence that guarantees all processes can finish without deadlock."
        ], explanation: 'Safe does not mean that every possible scheduling order works, or merely that no process is deadlocked now; one complete feasible ordering is enough.', tags: ['Operating systems', 'Deadlock avoidance', "Banker's algorithm", 'Safe state'] },
    'cs-q-404': { question: 'Which atomic-operation order protects a critical section with binary semaphore $S$ initialized to 1?', options: ['V(S) before entry and P(S) after exit', 'P(S) before entry and V(S) after exit', 'V(S) both before and after', 'P(S) both before and after'], solution: [
            "Acquire one permit before entering and return it after leaving.",
            "P(S) before entry and V(S) after exit",
            "P(S), or wait, acquires the semaphore; V(S), or signal, releases it."
        ], explanation: 'A common reversal is to treat V as validation before entry. With an initial value of 1, P must consume the only permit before the critical section and V must return it afterward.', tags: ['Process synchronization', 'Semaphore', 'Critical section', 'Atomic operation'] },
    'cs-q-405': { question: 'In the five-state process model, where does a Running process go after issuing a disk-read request?', options: ['Immediately to Ready for another time slice', 'To Waiting/Blocked until the I/O completion interrupt moves it back to Ready', 'Immediately to Terminated', 'It remains Running and busy-waits without releasing the CPU'], solution: [
            "Determine whether the process can make progress before the external I/O event completes.",
            "To Waiting/Blocked until the I/O completion interrupt moves it back to Ready",
            "The process blocks while waiting for I/O and returns to Ready after completion."
        ], explanation: 'I/O completion does not send the process straight back to Running: the interrupt only makes it Ready, and the scheduler must dispatch it again.', tags: ['Operating systems', 'Process states', 'Five-state model', 'I/O blocking'] },
    'cs-q-406': { question: 'How does the Linux Completely Fair Scheduler (CFS) choose the next task?', options: ['It uses FIFO and always picks the longest waiter.', 'It stores runnable tasks in a red-black tree keyed by vruntime and selects the leftmost task with the smallest vruntime.', 'It picks a random ready task.', 'It prioritizes the process with the shortest source code.'], solution: [
            "Inspect the minimum vruntime among runnable tasks.",
            "It stores runnable tasks in a red-black tree keyed by vruntime and selects the leftmost task with the smallest vruntime.",
            "CFS schedules the leftmost red-black-tree node, using weighted virtual runtime to approximate fair CPU sharing."
        ], explanation: 'The leftmost node is not necessarily the task that waited longest in wall-clock time; `vruntime` advances at a weight-adjusted rate, so nice values affect the comparison.', tags: ['Operating systems', 'Linux scheduler', 'CFS', 'Red-black tree', 'vruntime'] },
    'cs-q-407': { question: 'What is the defining design and memory advantage of an Inverted Page Table (IPT)?', options: ['It removes virtual memory and exposes only physical addresses.', 'One system-wide table is indexed by physical frame; each entry records the owning PID and VPN, so table size scales with physical RAM and a hash anchor accelerates lookup.', 'It keeps only SSD data and clears RAM.', 'It shortens every virtual address to eight bits.'], solution: [
            "Count entries by physical frames rather than by each process virtual page.",
            "One system-wide table is indexed by physical frame; each entry records the owning PID and VPN, so table size scales with physical RAM and a hash anchor accelerates lookup.",
            "An IPT bounds page-table storage by physical memory size and uses hashed PID/VPN lookup for translation."
        ], explanation: 'Do not allocate an IPT entry for every virtual page: its defining economy comes from one entry per physical frame, at the cost of needing PID/VPN lookup rather than direct VPN indexing.', tags: ['Virtual memory', 'Inverted page table', 'Hashed page table', 'Physical frames'] },
    'cs-q-408': { question: 'How does an MLFQ scheduler prevent a long-running CPU-bound task from starving in a low-priority queue?', options: ['It kills every CPU-bound task.', 'A periodic priority boost, or aging, returns tasks to the highest-priority queue so neglected jobs run again.', 'It sets the top-queue time slice to zero.', 'It permanently ignores every upper queue.'], solution: [
            "Restore priority after a bounded waiting interval rather than leaving demotion permanent.",
            "A periodic priority boost, or aging, returns tasks to the highest-priority queue so neglected jobs run again.",
            "Periodic priority boosts prevent starvation while preserving MLFQ responsiveness."
        ], explanation: 'Changing only a low-queue time slice does not cure starvation if upper queues stay busy; the neglected task must eventually regain scheduling priority.', tags: ['Operating systems', 'CPU scheduling', 'MLFQ', 'Aging', 'Starvation prevention'] },
    'cs-q-409': { question: 'Why can POSIX shared memory through `shmget` or `mmap` provide very high-throughput, low-latency IPC?', options: ['It automatically backs up data to a cloud database.', 'Both processes map the same physical pages, so writes become visible without copying payloads through kernel buffers; synchronization still requires a semaphore or mutex.', 'It uses no physical RAM and stores everything in CPU registers.', 'It is permanently read-only.'], solution: [
            "Count payload copies between producer and consumer address spaces.",
            "Both processes map the same physical pages, so writes become visible without copying payloads through kernel buffers; synchronization still requires a semaphore or mutex.",
            "Mapping the same physical pages into multiple processes provides zero-copy data transfer, with explicit synchronization for correctness."
        ], explanation: 'Shared pages remove payload copies, not races: visibility alone does not make a multi-field update atomic or tell the reader when a record is complete.', tags: ['Operating systems', 'IPC', 'Shared memory', 'Zero copy', 'mmap'] },
    'cs-q-410': { question: "When should the Banker's algorithm grant a process resource request?", options: ['Whenever Available is at least the request amount.', 'Only after a trial allocation shows a safe sequence $\\langle P_1,P_2,\\ldots,P_n\\rangle$ in which each remaining Need can be satisfied.', 'According to a coin toss.', 'Never, because refusing every request prevents deadlock.'], solution: [
            "Simulate the allocation, then repeatedly find a process whose Need is no more than current Work.",
            "Only after a trial allocation shows a safe sequence $\\langle P_1,P_2,\\ldots,P_n\\rangle$ in which each remaining Need can be satisfied.",
            "The request is granted only if the resulting state remains safe and has a complete safe sequence."
        ], explanation: '`Request <= Available` is necessary but not sufficient; consuming those resources can leave every unfinished process with a Need greater than the remaining Work.', tags: ['Operating systems', 'Deadlock', 'Deadlock avoidance', "Banker's algorithm", 'Safe sequence'] },
    'cs-q-411': { question: 'What is the main architecture benefit of Linux `sendfile()` with scatter-gather DMA compared with `read()` plus `write()`?', options: ['File data can stay in kernel page-cache and socket paths instead of visiting user space, and DMA can transfer descriptors without CPU payload copies.', 'The file is encrypted into unreadable noise.', 'The disk spins ten times faster.', 'Transfers are truncated above 1 KB.'], solution: [
            "Trace the data path and count user/kernel crossings and payload copies.",
            "File data can stay in kernel page-cache and socket paths instead of visiting user space, and DMA can transfer descriptors without CPU payload copies.",
            "`sendfile()` removes user-space staging and lets kernel and DMA paths deliver file data with far less CPU copying."
        ], explanation: '“Zero copy” does not mean that no hardware moves bytes; it means the payload avoids the extra kernel-to-user and user-to-kernel copies of a `read()`/`write()` loop.', tags: ['Operating systems', 'sendfile', 'Zero copy', 'DMA', 'Page cache', 'High-performance I/O'] },
    'cs-q-412': { question: 'How do Linux `kswapd` and direct reclaim respond as free memory crosses watermarks?', options: ['Below the low watermark, `kswapd` reclaims in the background; below the min watermark, the allocating task performs synchronous direct reclaim and may suffer a latency spike.', 'The machine reboots as soon as memory runs low.', 'Every application immediately receives SIGKILL.', 'Linux permits unlimited physical-RAM overdraft.'], solution: [
            "Compare free pages against low and min watermarks.",
            "Below the low watermark, `kswapd` reclaims in the background; below the min watermark, the allocating task performs synchronous direct reclaim and may suffer a latency spike.",
            "`kswapd` handles background pressure, while direct reclaim stalls the requesting process under critical pressure."
        ], explanation: 'Do not merge the low and min thresholds: crossing low wakes background reclaim, whereas crossing min can charge reclamation latency directly to the allocating task.', tags: ['Linux kernel', 'Memory management', 'kswapd', 'Direct reclaim', 'Page cache', 'OOM', 'Performance tuning'] },
    'cs-q-413': { question: 'How does Linux `epoll` avoid the $O(N)$ full-descriptor scan performed by `select` and `poll`?', options: ['A kernel red-black tree retains registrations, callbacks add ready sockets to a ready list, and `epoll_wait()` returns that list without rescanning every connection.', 'It abandons TCP and uses fax machines.', 'It permits only one client.', 'It writes every connection to `/tmp` and searches with grep.'], solution: [
            "Separate the persistent interest set from the list of descriptors that became ready.",
            "A kernel red-black tree retains registrations, callbacks add ready sockets to a ready list, and `epoll_wait()` returns that list without rescanning every connection.",
            "`epoll` maintains registrations in the kernel and reports callback-populated readiness, scaling with active events rather than all connections."
        ], explanation: '`epoll` avoids rescanning idle registrations; it does not make socket I/O itself constant-time, and a large ready set still costs work proportional to the events returned.', tags: ['Operating systems', 'epoll', 'select', 'poll', 'I/O multiplexing', 'Red-black tree', 'C10K'] },
    'cs-q-414': { question: 'Which statement correctly distinguishes a Linux-kernel spinlock from a mutex?', options: ['A spinlock busy-waits with atomic instructions and must guard a very short, non-sleeping section, including interrupt contexts; a contended mutex sleeps and therefore cannot be used in interrupt context.', 'A spinlock works only on one CPU and burns a multicore processor.', 'A contended mutex consumes 100% CPU forever.', 'Interrupt handlers should use mutexes because they may sleep for minutes.'], solution: [
            "Ask whether the current context is allowed to sleep and how long the lock may be held.",
            "A spinlock busy-waits with atomic instructions and must guard a very short, non-sleeping section, including interrupt contexts; a contended mutex sleeps and therefore cannot be used in interrupt context.",
            "Spinlocks avoid context switches but forbid sleeping; mutexes yield the CPU and require a sleepable process context."
        ], explanation: 'A spinlock is not simply a faster mutex: holding it across a sleep or long operation can waste a CPU or deadlock an interrupt path, so context and hold time decide the lock type.', tags: ['Operating systems', 'Linux kernel', 'Spinlock', 'Mutex', 'Interrupt context', 'CAS'] },
    'cs-q-415': { question: 'Why can 2 MB or 1 GB huge pages improve a large database or distributed-training workload?', options: ['A finite TLB covers far more virtual memory per entry—2 MB pages increase reach 512× over 4 KB pages—reducing TLB misses, page walks, and page-table memory.', 'They convert all data to audio in a speaker.', 'They multiply disk capacity by 100.', 'They prevent the OS from using physical memory.'], solution: [
            "Compute TLB reach as entry count multiplied by page size.",
            "A finite TLB covers far more virtual memory per entry\u20142 MB pages increase reach 512\u00D7 over 4 KB pages\u2014reducing TLB misses, page walks, and page-table memory.",
            "Huge pages expand TLB coverage and reduce expensive multilevel page-table walks."
        ], explanation: 'The benefit comes from greater TLB reach, not faster DRAM; workloads with sparse allocations may instead pay for internal fragmentation and harder large-page allocation.', tags: ['Operating systems', 'Memory management', 'Huge pages', 'TLB', 'MMU', 'Page table', 'Performance tuning'] },
    'cs-q-416': { question: 'How can Linux Lockdep warn about a potential ABBA deadlock before tasks actually block?', options: ['It assigns lock classes, records nested acquisition-order edges in a global dependency graph, and reports a cycle such as $A\\to B$ and $B\\to A$ with lock stacks.', 'It replaces every mutex with integer 1.', 'It physically cools the motherboard after detecting deadlock.', 'It permits only one global lock and bans concurrency.'], solution: [
            "Add each observed held-lock \u2192 acquired-lock edge and test whether the new edge closes a cycle.",
            "It assigns lock classes, records nested acquisition-order edges in a global dependency graph, and reports a cycle such as $A\\to B$ and $B\\to A$ with lock stacks.",
            "Lockdep performs cycle detection on the lock-class dependency graph and exposes inconsistent acquisition order early."
        ], explanation: 'Lockdep can flag a possible cycle even when no thread is currently blocked: opposite observed acquisition orders are enough to prove that some interleaving could deadlock.', tags: ['Operating systems', 'Linux kernel', 'Lockdep', 'Deadlock', 'DAG', 'Directed graph', 'Topological order'] },
};
