import type { CsQuestionEnglishRegistry } from './csQuestionCopyTypes';
export const CS_QUESTION_COPY_UNIT_7: CsQuestionEnglishRegistry = {
    'cs-q-701': { question: 'Why does scaled dot-product attention compute $\\text{softmax}(QK^T/\\sqrt{d_k})V$ instead of applying softmax directly to $QK^T$?', options: ['To truncate matrix dimensions to integers for an integer ALU', 'To keep high-dimensional dot products from driving softmax into saturated regions with tiny gradients', 'To force every attention weight to zero', 'To reverse the eigenvalues and prevent overflow'], solution: [
            "Estimate how the variance of a dot product grows with key dimension $d_k$.",
            "To keep high-dimensional dot products from driving softmax into saturated regions with tiny gradients",
            "Dividing by $\\sqrt{d_k}$ stabilizes logit scale and preserves useful softmax gradients."
        ], explanation: 'The scale uses key width $d_k$, not sequence length, and it changes logit magnitude rather than matrix dimensions; without it, variance grows with every summed feature.', tags: ['Transformer', 'Self-attention', 'Scaled dot product', 'Gradient stability'] },
    'cs-q-702': { question: 'What is the primary purpose of a KV cache during autoregressive LLM generation?', options: ['Burn every model weight into CPU ROM.', 'Store Key and Value projections for prior tokens so each next token does not recompute the entire prefix.', 'Upload every user prompt to a public cloud.', 'Delete every neuron with attention below 0.1.'], solution: [
            "Separate the unchanged prefix K/V tensors from the Query for the newly generated token.",
            "Store Key and Value projections for prior tokens so each next token does not recompute the entire prefix.",
            "A KV cache exchanges memory for much less repeated attention computation during decoding."
        ], explanation: 'The cache stores prior K/V projections, not model weights, Queries, or final attention scores; its speedup therefore comes with memory growth per layer and generated token.', tags: ['LLM inference', 'KV cache', 'Autoregressive generation', 'Performance optimization'] },
    'cs-q-703': { question: 'What geometric advantage does Rotary Position Embedding (RoPE) have over a learned absolute position vector?', options: ['It adds the same constant vector to every token.', 'It rotates Query and Key pairs in two-dimensional subspaces so their dot product depends naturally on relative offset $m-n$.', 'It randomly shuffles context order.', 'It supports only sequences shorter than 512 tokens.'], solution: [
            "Write each position as a phase rotation and inspect the relative phase inside the Q\u2013K inner product.",
            "It rotates Query and Key pairs in two-dimensional subspaces so their dot product depends naturally on relative offset $m-n$.",
            "RoPE encodes relative displacement through rotation, supporting distance-aware attention and useful context extrapolation."
        ], explanation: 'RoPE does not insert an explicit relative-position lookup table: relative offset emerges when the two absolute phase rotations meet in the Q–K dot product, and that alone does not guarantee unlimited extrapolation.', tags: ['RoPE', 'Rotary position embedding', 'Relative position', 'Long-context LLM'] },
    'cs-q-704': { question: 'What simplification does Direct Preference Optimization (DPO) make relative to PPO-based RLHF?', options: ['It trains five extra reward models and uses ten times more memory.', 'It optimizes chosen-versus-rejected pairs directly against a reference policy, without a separate reward model or unstable PPO sampling loop.', 'It requires no preference comparisons.', 'It works only for code generation.'], solution: [
            "Use the closed-form relation between an optimal policy and its implicit reward.",
            "It optimizes chosen-versus-rejected pairs directly against a reference policy, without a separate reward model or unstable PPO sampling loop.",
            "DPO turns preference alignment into a stable paired classification loss over policy log-probability ratios."
        ], explanation: 'Removing PPO does not remove supervision or the reference policy: DPO still needs chosen/rejected pairs and compares policy log-ratios against a fixed reference.', tags: ['LLM alignment', 'DPO', 'RLHF', 'Human preference', 'Machine learning'] },
    'cs-q-705': { question: 'Why does enterprise Retrieval-Augmented Generation commonly use coarse retrieval followed by fine reranking?', options: ['A bi-encoder retrieves many candidates cheaply, then a cross-encoder jointly scores each query-document pair for higher precision.', 'It removes the language model and returns raw database text.', 'Users must memorize every document UUID.', 'Every document on disk is inserted into the context for every question.'], solution: [
            "Assign the scalable first stage to independent embeddings and reserve cross-attention for a small candidate set.",
            "A bi-encoder retrieves many candidates cheaply, then a cross-encoder jointly scores each query-document pair for higher precision.",
            "The two-stage design combines million-scale retrieval throughput with accurate semantic reranking."
        ], explanation: 'A reranker can reorder only what coarse retrieval supplies; if the relevant document misses the candidate set, the expensive second stage cannot recover it.', tags: ['RAG', 'Vector retrieval', 'Cross-encoder', 'Semantic reranking', 'Knowledge base'] },
    'cs-q-706': { question: 'How can a selective state-space model such as Mamba achieve $O(N)$ sequence scaling instead of Transformer attention at $O(N^2)$?', options: ['Limit every text to 128 characters.', 'Use input-dependent state-space parameters with a fixed-size recurrent state and a hardware-aware associative scan for parallel training.', 'Convert text to MP3.', 'Discard a random 90% of tokens.'], solution: [
            "Express sequence processing as a discretized state recurrence rather than an all-pairs attention matrix.",
            "Use input-dependent state-space parameters with a fixed-size recurrent state and a hardware-aware associative scan for parallel training.",
            "Selective state updates retain relevant inputs while linear scans avoid the quadratic attention matrix."
        ], explanation: 'Linear scaling comes from compressing history into a fixed-size recurrent state, not from computing cheaper all-pairs attention; that compression changes the model’s memory trade-offs.', tags: ['Frontier AI', 'Mamba', 'SSM', 'State-space model', 'Linear complexity'] },
    'cs-q-707': { question: 'What loop defines the ReAct framework for autonomous or multi-agent systems?', options: ['Click random interface controls without reasoning.', 'Alternate Thought, Action, and Observation, using each observation to correct the next reasoning step.', 'Delete all server code after an error.', 'Restrict the system to one-turn questions.'], solution: [
            "Pair an internal decision with an external tool action, then feed the observed result into the next cycle.",
            "Alternate Thought, Action, and Observation, using each observation to correct the next reasoning step.",
            "ReAct closes the loop between reasoning and evidence-producing actions, enabling traceable self-correction."
        ], explanation: 'A Thought–Action trace without a real Observation is still an unverified guess; the corrective value comes from feeding tool or environment evidence into the next decision.', tags: ['AI agents', 'ReAct', 'Multi-agent', 'Tool use', 'Self-correction'] },
    'cs-q-708': { question: 'How does StreamingLLM keep a fixed-size sliding KV window stable for effectively unbounded text?', options: ['It permanently retains a few initial attention-sink tokens plus recent window tokens, preserving the softmax distribution when old middle tokens leave.', 'It sets every attention weight to 1.0.', 'It retrains the full model whenever the cache fills.', 'It replaces all letters with digits.'], solution: [
            "Preserve the initial tokens that absorb otherwise diffuse attention mass before sliding the recent window.",
            "It permanently retains a few initial attention-sink tokens plus recent window tokens, preserving the softmax distribution when old middle tokens leave.",
            "Attention-sink tokens stabilize streaming inference without growing KV memory with total history."
        ], explanation: 'Attention sinks need not contain the most important semantics; they absorb normalization mass. Keeping them stabilizes attention, but discarded middle tokens are still no longer available as content.', tags: ['Long-context inference', 'StreamingLLM', 'Attention sink', 'KV cache'] },
    'cs-q-709': { question: 'What does Medusa change compared with speculative decoding that uses a separate draft model?', options: ['It attaches several future-token prediction heads to the frozen target model and verifies a candidate tree with tree attention in one pass.', 'It randomly drops 90% of layer weights.', 'It stores every weight as HTML.', 'It restricts output to yes or no.'], solution: [
            "Generate several branching future-token candidates from the target hidden state before one parallel verification pass.",
            "It attaches several future-token prediction heads to the frozen target model and verifies a candidate tree with tree attention in one pass.",
            "Medusa avoids maintaining a separate draft model while retaining lossless target-model verification and higher decoding throughput."
        ], explanation: 'The extra heads only propose branches; they cannot bypass target-model verification. Rejected candidates provide no output speedup and must be discarded to preserve target behavior.', tags: ['Inference acceleration', 'Medusa', 'Speculative decoding', 'Tree attention', 'Lossless acceleration'] },
    'cs-q-710': { question: 'How does a Vision Transformer (ViT) feed a two-dimensional image into a standard Transformer encoder?', options: ['Split the image into fixed patches such as $16\\times16$, flatten and linearly project them into tokens, add `[CLS]` and position embeddings, then apply self-attention.', 'Average every pixel into one gray value.', 'Convert the image to WAV audio.', 'Keep only the center pixel.'], solution: [
            "Convert the image grid into an ordered sequence of equal-dimensional patch embeddings.",
            "Split the image into fixed patches such as $16\\times16$, flatten and linearly project them into tokens, add `[CLS]` and position embeddings, then apply self-attention.",
            "ViT treats projected image patches as tokens and learns global visual relationships with Transformer attention."
        ], explanation: 'Patch size is not cosmetic: larger patches shorten the token sequence and attention cost but can erase fine spatial detail before the Transformer sees it.', tags: ['Frontier AI', 'Vision Transformer', 'ViT', 'Multimodal AI', 'Patch embedding', 'VLM'] },
    'cs-q-711': { question: 'How does the closed-form DPO objective eliminate the reward-model and PPO stages of conventional RLHF?', options: ['It represents implicit reward as $\\beta\\log\\frac{\\pi_\\theta(y|x)}{\\pi_{\\text{ref}}(y|x)}$ and trains a binary chosen-versus-rejected preference loss.', 'It stops alignment entirely.', 'People manually edit every network weight.', 'A random number labels every answer.'], solution: [
            "Substitute the optimal policy\u2013reward relation into the Bradley\u2013Terry preference likelihood.",
            "It represents implicit reward as $\\beta\\log\\frac{\\pi_\\theta(y|x)}{\\pi_{\\text{ref}}(y|x)}$ and trains a binary chosen-versus-rejected preference loss.",
            "DPO reduces alignment to one stable supervised preference objective based on policy and reference log-probability ratios."
        ], explanation: 'The reference-policy denominator is essential: using only the current policy’s chosen/rejected probabilities drops the implicit KL anchor and is not the stated DPO objective.', tags: ['LLM alignment', 'DPO', 'RLHF', 'PPO', 'Preference optimization', 'Bradley-Terry'] },
    'cs-q-712': { question: 'What advantage does NTK-aware RoPE scaling have over uniform linear position interpolation for 32K–128K contexts?', options: ['It preserves high-frequency dimensions for local token precision while stretching low-frequency dimensions for long-range coverage.', 'It reads all text backward.', 'It deletes punctuation.', 'It shuffles token order for every inference.'], solution: [
            "Separate rotary dimensions by frequency instead of scaling every positional frequency equally.",
            "It preserves high-frequency dimensions for local token precision while stretching low-frequency dimensions for long-range coverage.",
            "NTK-aware scaling protects local syntax while extending low-frequency phase range for longer contexts."
        ], explanation: 'Uniformly stretching every rotary frequency can blur short-range position cues; NTK-aware scaling treats fast local phases differently from slow long-range phases.', tags: ['Frontier AI', 'RoPE', 'NTK-aware scaling', 'Long context', 'NIAH', 'Position extrapolation'] },
    'cs-q-713': { question: 'How can grammar-guided constrained decoding guarantee output that conforms to a JSON Schema or SQL grammar?', options: ['Compile the grammar to an automaton and set logits of every illegal next token to $-\\infty$ before sampling.', 'Restart the computer whenever output is malformed.', 'Have an engineer type over every token.', 'Replace the model with one fixed response.'], solution: [
            "Track the parser state after each emitted token and enumerate only transitions valid from that state.",
            "Compile the grammar to an automaton and set logits of every illegal next token to $-\\infty$ before sampling.",
            "Dynamic logit masking restricts generation to grammar-valid continuations, guaranteeing syntactic compliance without retries."
        ], explanation: 'Grammar constraints guarantee form, not truth: a decoder can emit schema-valid JSON with invented values, and only tokens legal in the current parser state are masked in.', tags: ['Frontier AI', 'Constrained decoding', 'JSON Schema', 'DFA', 'Logit masking', 'Structured output'] },
    'cs-q-714': { question: 'How does Grouped-Query Attention (GQA) trade off MHA quality and MQA KV-cache size?', options: ['MHA gives each Query head its own K/V head; MQA shares one K/V head globally; GQA shares each K/V head within a group, so $1<H_{kv}<H_q$.', 'It removes Key and Value matrices.', 'It turns every history token into binary zero.', 'It limits every sentence to ten words.'], solution: [
            "Count K/V heads cached per layer under MHA, MQA, and GQA.",
            "MHA gives each Query head its own K/V head; MQA shares one K/V head globally; GQA shares each K/V head within a group, so $1<H_{kv}<H_q$.",
            "GQA retains multiple K/V representations for quality while reducing KV memory roughly by the Query-to-KV head sharing ratio."
        ], explanation: 'GQA groups Query heads around shared K/V heads; it does not merge Query heads or group tokens. Cache savings depend on $H_{kv}/H_q$, not on sequence chunking.', tags: ['Frontier AI', 'GQA', 'MHA', 'MQA', 'KV cache', 'Transformer', 'Long-context inference'] },
    'cs-q-715': { question: 'How does Group Relative Policy Optimization (GRPO) remove the large critic model used by PPO?', options: ['Sample a group of answers for one prompt and normalize each reward by the group mean and standard deviation: $A_i=(r_i-\\text{mean})/\\text{std}$.', 'Remove the reward function.', 'Sample only one character per problem.', 'Adjust every network parameter manually.'], solution: [
            "Use within-group reward statistics as the baseline for each sampled response.",
            "Sample a group of answers for one prompt and normalize each reward by the group mean and standard deviation: $A_i=(r_i-\\text{mean})/\\text{std}$.",
            "GRPO estimates relative advantages from peer samples, saving critic memory while retaining a policy-gradient learning signal."
        ], explanation: 'Removing the critic does not remove the reward signal: GRPO needs several comparable samples, and an equal-reward group yields little or no relative-advantage information.', tags: ['Frontier AI', 'GRPO', 'PPO', 'Reinforcement learning', 'RLHF', 'Relative advantage', 'Reasoning model'] },
    'cs-q-716': { question: 'What is the key Mamba advance over time-invariant S4 and conventional linear attention?', options: ['Make state-space parameters input-dependent so the model selects what to retain, then use a hardware-aware parallel associative scan for efficient GPU training and constant-state decoding.', 'Require reptile-inspired biological neurons.', 'Replace numerical matrices with text puzzles.', 'Require exactly seven input words.'], solution: [
            "Let the input control the state transition and read/write parameters, then scan the recurrence in parallel during training.",
            "Make state-space parameters input-dependent so the model selects what to retain, then use a hardware-aware parallel associative scan for efficient GPU training and constant-state decoding.",
            "Selective state spaces combine content-dependent memory with $O(N)$ training and $O(1)$ recurrent inference state."
        ], explanation: '$O(1)$ recurrent state does not mean an entire length-$N$ sequence costs $O(1)$ time or that all past tokens remain explicitly recoverable; the state is a learned compression of history.', tags: ['Frontier AI', 'Mamba', 'SSM', 'State-space model', 'Associative scan', 'Long context'] },
};
