import type { CsQuestionEnglishRegistry } from './csQuestionCopyTypes';
export const CS_QUESTION_COPY_MOCKS: CsQuestionEnglishRegistry = {
    'cs-mock-m1': { question: 'What is the central innovation of the Von Neumann computer architecture?', options: ['Program instructions and data are both stored as binary in one addressable memory for the CPU to fetch and execute.', 'Every instruction requires physically rewiring a dedicated circuit.', 'A CPU needs no registers or clock.', 'A computer can process only analog signals.'], solution: ["The stored-program concept places both instructions and data in shared memory."], explanation: 'Stored-program does not mean that code and data are semantically interchangeable; it means the CPU can fetch encoded instructions from the same addressable memory system instead of being rewired for each program.', tags: ['Von Neumann architecture', 'Stored program'] },
    'cs-mock-m2': { question: 'What is the basic order of a typical CPU instruction cycle?', options: ['Decode ➜ Fetch ➜ Writeback ➜ Execute', 'Fetch ➜ Decode ➜ Execute ➜ Writeback', 'Execute ➜ Decode ➜ Fetch ➜ Writeback', 'Writeback ➜ Execute ➜ Decode ➜ Fetch'], solution: ["The standard order is Fetch, Decode, Execute, and Writeback."], explanation: 'A pipeline may overlap these stages across several instructions, but one instruction still has to be fetched before it can be decoded, and its result cannot be written back before execution.', tags: ['Instruction cycle', 'Control unit'] },
    'cs-mock-m3': { question: "When two positive 8-bit two's-complement integers are added, which result indicates arithmetic overflow?", options: ['The sign bit becomes 1 and the result appears negative.', 'The sign bit remains 0.', 'Every bit becomes 0.', 'The result magnitude is smaller than either operand.'], solution: ["A negative sign after adding two positive values means the true sum exceeded the positive range."], explanation: 'A carry out of the most significant bit is not the signed-overflow test; overflow is detected when same-sign operands produce a result with the opposite sign.', tags: ["Two's complement", 'Overflow'] },
    'cs-mock-m4': { question: 'What is the main purpose of a Translation Lookaside Buffer (TLB) in virtual memory?', options: ['Permanently back up every user file.', 'Cache recent Virtual Page Number to Physical Frame Number translations in hardware.', 'Block viruses from entering the kernel.', 'Compress downloaded video automatically.'], solution: ["A TLB accelerates virtual-to-physical address translation."], explanation: 'A TLB caches address mappings, not the referenced instructions or data; a TLB miss can be resolved by a page-table walk and is not automatically a page fault.', tags: ['Operating systems', 'Virtual memory', 'TLB'] },
    'cs-mock-f1': { question: 'Why do multiplayer action games and real-time voice often prefer UDP to TCP?', options: ['UDP avoids connection setup and mandatory retransmission, minimizing latency.', 'UDP always includes the strongest AES encryption.', 'UDP guarantees zero loss and strict ordering.', 'TCP cannot carry packets over IPv4.'], solution: ["UDP removes handshake and retransmission overhead, favoring real-time delivery."], explanation: 'UDP does not guarantee that a packet is timely, ordered, or delivered; the application accepts that trade-off and often adds sequence numbers, jitter handling, or selective recovery itself.', tags: ['Computer networks', 'TCP/UDP', 'Protocol'] },
    'cs-mock-f2': { question: 'Why can a GPU Tensor Core greatly outperform a conventional CPU core on $D=A\\times B+C$?', options: ['It performs many small dense fused matrix multiply-accumulate operations in parallel each hardware cycle.', 'It runs without electrical power.', 'One core clocks at 100 GHz.', 'It contains hundreds of terabytes of mechanical disks.'], solution: ["Tensor cores implement highly parallel matrix FMA datapaths in hardware."], explanation: 'Tensor-core throughput applies to supported dense tile shapes and precisions; it is not a generally faster replacement for a CPU on branchy, serial, or irregular work.', tags: ['GPU', 'Tensor core', 'Matrix multiplication'] },
    'cs-mock-f3': { question: 'What is the time complexity of standard full self-attention in sequence length $N$?', options: ['$O(N)$', '$O(N^2)$', '$O(\\log N)$', '$O(1)$'], solution: ["The all-pairs attention score matrix requires $O(N^2)$ work."], explanation: 'A causal mask removes future-token values but still considers a triangular number of token pairs, so it changes the constant rather than the quadratic order.', tags: ['Transformer', 'Self-attention', 'Complexity'] },
    'cs-mock-f4': { question: 'What engineering benefit does a KV cache provide during LLM inference?', options: ['It avoids recomputing the entire history at every new token, reducing autoregressive decoding time.', 'It uploads all model weights to a shared cloud.', 'It removes Python syntax errors.', 'It quadruples display resolution.'], solution: ["KV caching trades memory for much faster incremental generation."], explanation: 'The cache speeds token-by-token decode, not the initial prefill of an unseen prompt, and its per-layer Key/Value storage grows with batch size and retained context.', tags: ['LLM inference', 'KV cache', 'Performance optimization'] },
};
