import type { CsQuestionEnglishRegistry } from './csQuestionCopyTypes';
export const CS_QUESTION_COPY_UNIT_6: CsQuestionEnglishRegistry = {
    'cs-q-601': { question: 'Why do deep-learning training and inference rely heavily on GPUs rather than CPUs?', options: ['A CPU has more cores than a GPU but a lower clock.', 'A GPU combines thousands of throughput-oriented SIMT lanes, high memory bandwidth, and tensor units suited to massive GEMM workloads.', 'A GPU supports only FP64 and cannot execute FP16.', 'A CPU has no caches and is therefore ten thousand times slower.'], solution: [
            "Compare silicon devoted to control latency with silicon devoted to parallel arithmetic throughput.",
            "GPUs organize many parallel lanes and tensor cores around high-throughput matrix multiplication."
        ], explanation: 'Core count alone is not the reason: GPUs win when the work exposes regular, high-occupancy data parallelism; branch-heavy serial control can still favor a latency-oriented CPU.', tags: ['AI hardware', 'GPU', 'Matrix operations', 'GEMM'] },
    'cs-q-602': { question: 'A 70-billion-parameter model needs about 140 GB for FP16 weights. Approximately how much storage do INT4 weights require at 0.5 Bytes per parameter?', options: ['About 70 GB', 'About 35 GB', 'About 18 GB', 'About 14 GB'], solution: [
            "INT4 stores four bits, or 0.5 Bytes, per parameter.",
            "Multiply 70 billion parameters by 0.5 Bytes.",
            "$70\\times0.5=35$ billion Bytes.",
            "The weights therefore require about 35 GB before metadata and runtime buffers."
        ], explanation: 'The easy unit mistake is to read INT4 as four Bytes instead of four bits: it is one quarter of FP16 weight storage, while scales, zero-points, KV cache, and allocator overhead are extra.', tags: ['Model quantization', 'INT4', 'VRAM optimization', 'LLM inference'] },
    'cs-q-603': { question: 'What happens when threads in one CUDA warp take opposite sides of `if (threadIdx.x % 2 == 0) { ... } else { ... }`?', options: ['All 32 threads have independent program counters and execute both paths concurrently at full speed.', 'Warp divergence serializes the two paths under different active masks, roughly halving useful lane utilization in the branch.', 'The GPU raises an exception and resets its driver.', 'The warp merges all operations and finishes in half the time.'], solution: [
            "Determine whether all 32 SIMT lanes share the same issued instruction at a given cycle.",
            "Warp divergence serializes the two paths under different active masks, roughly halving useful lane utilization in the branch.",
            "Divergent warp paths execute serially while lanes on the other path are masked off."
        ], explanation: 'Divergence is a within-warp problem: different warps may follow different paths independently, but disagreement among the 32 lanes sharing one issuer forces masked serial execution.', tags: ['GPU microarchitecture', 'CUDA', 'Warp divergence', 'SIMT'] },
    'cs-q-604': { question: 'What is the main purpose of a weight-stationary dataflow in a TPU systolic array?', options: ['Weights remain in processing-element registers while activations and partial sums flow, maximizing reuse and reducing off-chip traffic.', 'Every multiply immediately writes its weight back to DRAM.', 'Every multiplier restarts once per microsecond.', 'Weights are converted to audio and broadcast through speakers.'], solution: [
            "Choose which operand should remain local across the largest number of multiply-accumulate operations.",
            "Weights remain in processing-element registers while activations and partial sums flow, maximizing reuse and reducing off-chip traffic.",
            "Keeping weights in each PE reuses them many times and sharply reduces memory-access energy."
        ], explanation: 'Weight-stationary does not mean the whole model remains on chip; only the current weight tile stays local to each PE while other operands and later tiles continue to move.', tags: ['AI accelerator', 'TPU', 'Systolic array', 'Weight stationary', 'Low-power computing'] },
    'cs-q-605': { question: 'What is the key purpose of dynamic loss scaling in FP16/BF16 mixed-precision training?', options: ['Scale the loss upward so tiny back-propagated gradients remain representable instead of underflowing to zero in FP16.', 'Force the loss to become negative.', 'Delete every attention weight.', 'Randomly reset GPU memory during each backward pass.'], solution: [
            "Move small gradient magnitudes into the representable FP16 exponent range before backpropagation.",
            "Scale the loss upward so tiny back-propagated gradients remain representable instead of underflowing to zero in FP16.",
            "Loss scaling prevents FP16 gradient underflow, then the optimizer unscales gradients before updating higher-precision master weights."
        ], explanation: 'Scaling the loss does not improve the objective value; it temporarily rescales gradients. If the scale is too high, overflow is detected and the dynamic scale must be reduced before the update.', tags: ['Deep learning', 'Mixed precision', 'FP16', 'Loss scaling', 'GPU training'] },
    'cs-q-606': { question: 'In a Roofline model, what limits an operator whose arithmetic intensity $I$ lies below the ridge point $I_{\\text{knee}}$ on the sloped line?', options: ['Compute throughput; more memory bandwidth cannot help.', 'Memory bandwidth; compute units wait for data, so cache reuse or greater bandwidth is needed.', 'Network bandwidth; the fiber cable must be replaced.', 'Nothing; performance can grow without physical limit.'], solution: [
            "Compare attainable bandwidth \u00D7 arithmetic intensity with peak TFLOPS.",
            "Memory bandwidth; compute units wait for data, so cache reuse or greater bandwidth is needed.",
            "Below the ridge point, performance is memory-bound rather than compute-bound."
        ], explanation: 'Being below the ridge is about low FLOPs per Byte, not a slow arithmetic unit; raising peak TFLOPS alone leaves the sloped bandwidth ceiling unchanged.', tags: ['AI hardware', 'Roofline model', 'Memory bound', 'Arithmetic intensity', 'HBM'] },
    'cs-q-607': { question: 'For FP16 inference with $L=32$ layers, hidden width $h=4096$, batch $b=2$, and sequence length $s=8192$, approximately how much VRAM does the KV cache consume?', options: ['About 64 MB', 'About 2 GB', 'About 8.6 GB', 'About 64 GB'], solution: [
            "Count both Key and Value tensors with the leading factor 2.",
            "Substitute $b=2$, $s=8192$, $L=32$, $h=4096$, and 2 Bytes per FP16 element.",
            "$2\\times2\\times8192\\times32\\times4096\\times2=8,589,934,592$ Bytes.",
            "That is 8 GiB, approximately 8.59 GB."
        ], explanation: 'The common underestimate drops the leading factor of two for separate Key and Value tensors, or forgets that the cache is replicated across every layer and batch item.', tags: ['LLM inference', 'KV cache', 'Memory estimation', 'VRAM', 'Transformer'] },
    'cs-q-608': { question: 'Which operating-system idea does vLLM PagedAttention use to reduce KV-cache fragmentation?', options: ['Paging: split logical KV sequences into fixed blocks stored in noncontiguous VRAM and map them through block tables.', 'Disk defragmentation that pauses the GPU every five seconds.', 'RAID 0 replication from VRAM to disk.', 'CPU polling that reads one token at a time.'], solution: [
            "Separate contiguous logical token positions from the physical blocks that store them.",
            "Paging: split logical KV sequences into fixed blocks stored in noncontiguous VRAM and map them through block tables.",
            "Block-table indirection lets PagedAttention allocate, share, and reclaim KV blocks without requiring one contiguous region per request."
        ], explanation: 'This is paging as an allocation analogy inside GPU memory, not swapping KV data to disk; the block table decouples logical token order from noncontiguous VRAM blocks.', tags: ['vLLM', 'PagedAttention', 'KV cache', 'Virtual-memory paging', 'High-throughput inference'] },
    'cs-q-609': { question: 'What do NVLink and NVSwitch provide in an eight-GPU HGX training server beyond PCIe?', options: ['About 900 GB/s to 1.8 TB/s bidirectional GPU bandwidth and single-hop nonblocking connectivity for tensor-parallel and MoE collectives.', 'Text-file transfer only.', 'Wireless transport over Wi-Fi 6.', 'Automatic merging of all GPU memory into at most 16 MB.'], solution: [
            "Compare link bandwidth and hop topology for all-to-all accelerator communication.",
            "About 900 GB/s to 1.8 TB/s bidirectional GPU bandwidth and single-hop nonblocking connectivity for tensor-parallel and MoE collectives.",
            "NVLink plus NVSwitch forms a high-bandwidth full fabric that removes PCIe as the primary collective-communication bottleneck."
        ], explanation: 'A fast NVSwitch fabric does not automatically merge eight VRAMs into one transparent memory pool; software still partitions tensors and schedules collectives across devices.', tags: ['AI hardware', 'NVLink', 'NVSwitch', 'PCIe', 'GPU interconnect', 'All-to-all'] },
    'cs-q-610': { question: 'Which packaging technology lets HBM3e provide multi-terabyte-per-second bandwidth beside an AI accelerator?', options: ['TSVs vertically stack DRAM dies; micro-bumps connect the HBM stack and GPU on a silicon interposer through a very wide 1024-bit short-reach interface.', 'Long copper wires place memory outside the chassis.', 'Every memory die is immersed in liquid nitrogen.', 'The controller is removed and people enter data manually.'], solution: [
            "Trace thousands of short parallel signals through stacked dies and the 2.5D interposer.",
            "TSVs vertically stack DRAM dies; micro-bumps connect the HBM stack and GPU on a silicon interposer through a very wide 1024-bit short-reach interface.",
            "TSV stacking and interposer co-packaging create an ultra-wide, energy-efficient HBM interface that attacks the memory wall."
        ], explanation: 'The bandwidth comes from thousands of short parallel wires, not an extreme clock rate; HBM dies are stacked beside the accelerator on an interposer rather than inside the compute die.', tags: ['AI hardware', 'HBM3e', 'TSV', 'CoWoS', 'Advanced packaging', 'Memory wall', 'Silicon interposer'] },
    'cs-q-611': { question: 'What GPU-memory optimization lets FlashAttention-2 accelerate exact attention without materializing the full $N\\times N$ matrix in HBM?', options: ['Tile Q, K, and V into on-chip SRAM and maintain an online softmax with running maxima and normalization factors.', 'Remove softmax and return unnormalized weights.', 'Send all operations to the motherboard audio device.', 'Set every floating-point parameter to zero.'], solution: [
            "Partition attention into SRAM-sized tiles while carrying the numerically stable softmax state between tiles.",
            "Tile Q, K, and V into on-chip SRAM and maintain an online softmax with running maxima and normalization factors.",
            "SRAM tiling and online softmax minimize HBM traffic while preserving exact attention results."
        ], explanation: 'FlashAttention is not a sparse or approximate attention shortcut: the running maximum and normalization sum let tiled softmax reproduce the exact result without storing the full score matrix.', tags: ['AI hardware', 'FlashAttention', 'SRAM', 'HBM', 'Online softmax', 'Tiling', 'Kernel fusion'] },
    'cs-q-612': { question: 'What insight lets Activation-aware Weight Quantization (AWQ) retain accuracy at INT4 better than naive round-to-nearest?', options: ['A small fraction of salient weight channels matter disproportionately, and activation magnitudes identify them; scaling protects those channels during quantization.', 'Weights are converted to text.', 'Inference requires ten supercomputers.', 'Half the neurons are randomly set to zero.'], solution: [
            "Measure which weight channels multiply large activation features in calibration data.",
            "A small fraction of salient weight channels matter disproportionately, and activation magnitudes identify them; scaling protects those channels during quantization.",
            "AWQ protects roughly the most activation-sensitive 1% of channels, allowing aggressive 4-bit quantization with little perplexity loss."
        ], explanation: 'AWQ is not pruning and does not simply leave salient weights in FP16; calibration activations reveal sensitive channels, and per-channel scaling redistributes their quantization error.', tags: ['LLM inference', 'Quantization', 'AWQ', 'INT4', 'Activation aware', 'Edge deployment', 'PTQ'] },
    'cs-q-613': { question: 'Why does FP8 define both E4M3 and E5M2 formats?', options: ['E4M3 uses three fraction bits for better precision over a smaller range, while E5M2 uses five exponent bits for the wider gradient range in backpropagation.', 'E4M3 handles integers and E5M2 handles only even numbers.', 'Hardware alternates the formats randomly.', 'E5M2 deliberately halves speed to save electricity.'], solution: [
            "Trade fraction precision against exponent dynamic range for forward tensors and backward gradients.",
            "E4M3 uses three fraction bits for better precision over a smaller range, while E5M2 uses five exponent bits for the wider gradient range in backpropagation.",
            "E4M3 suits precision-sensitive weights and activations; E5M2 suits gradients spanning more orders of magnitude."
        ], explanation: 'More exponent bits do not mean more overall precision: E5M2 buys range by giving up a fraction bit, whereas E4M3 resolves nearby values more finely within its smaller range.', tags: ['AI hardware', 'FP8', 'E4M3', 'E5M2', 'Transformer Engine', 'Mixed precision'] },
    'cs-q-614': { question: 'How does a 2D systolic array reduce register-file and memory bandwidth for matrix multiplication?', options: ['Inputs, weights, and partial sums move rhythmically between neighboring PEs, where multiply-accumulate results reuse operands without returning each intermediate value to a central register file.', 'It removes the clock and lets transistors discharge freely.', 'It permits only Boolean NOT.', 'It uses dry ice for optical transfer.'], solution: [
            "Follow each operand as a wavefront through multiple neighboring processing elements.",
            "Inputs, weights, and partial sums move rhythmically between neighboring PEs, where multiply-accumulate results reuse operands without returning each intermediate value to a central register file.",
            "Direct PE-to-PE dataflow maximizes on-chip reuse and drastically reduces central storage traffic."
        ], explanation: 'A systolic array does not reduce the number of multiply-accumulates; it reduces expensive data movement by reusing each arriving value across neighboring PEs.', tags: ['AI hardware', 'TPU', 'Systolic array', 'GEMM', 'Data reuse', 'MXU'] },
    'cs-q-615': { question: 'Why can an `if-else` branch cause severe warp divergence in NVIDIA SIMT execution?', options: ['All 32 lanes share an instruction issuer, so different paths are serialized under active masks and lanes on the other path sit idle.', 'The GPU reaches absolute zero.', 'All threads exit and format the disk.', 'Hardware replaces the branch with multiplication and skips it.'], solution: [
            "Determine whether every lane in the warp evaluates the same branch direction.",
            "All 32 lanes share an instruction issuer, so different paths are serialized under active masks and lanes on the other path sit idle.",
            "A divergent warp serializes each path, lowering useful lane throughput until the paths reconverge."
        ], explanation: 'The presence of an `if` is not enough to cause divergence: the penalty appears only when lanes of the same warp choose different paths; a warp-uniform branch stays efficient.', tags: ['AI hardware', 'GPU', 'CUDA', 'SIMT', 'Warp', 'Warp divergence', 'Branch divergence'] },
    'cs-q-616': { question: 'Why is coalesced global-memory access critical for CUDA bandwidth?', options: ['Aligned consecutive addresses from 32 warp lanes can fit one 128-byte transaction; strided or scattered accesses may expand into many 32-byte transactions with very low useful-byte efficiency.', 'Uncoalesced access reverses the GPU fan.', 'Coalescing makes the display monochrome.', 'The controller discards all uncoalesced writes.'], solution: [
            "Map every lane address onto the fixed 32- or 128-byte memory segments touched by the warp.",
            "Aligned consecutive addresses from 32 warp lanes can fit one 128-byte transaction; strided or scattered accesses may expand into many 32-byte transactions with very low useful-byte efficiency.",
            "Coalescing minimizes transaction count; scattered access transfers many mostly unused cache-line bytes and wastes HBM bandwidth."
        ], explanation: 'Coalescing is judged across the whole warp, not one thread at a time; even consecutive addresses can require extra transactions when the first address is badly misaligned.', tags: ['AI hardware', 'GPU', 'CUDA', 'Coalesced access', 'HBM', 'Memory bandwidth', 'Cache line'] },
};
