import { describe, it, expect } from 'vitest'

describe('Chemistry Nernst Equation & Concentration Cell Tests', () => {
  it('calculates the 25 °C Nernst slope factor (2.303 * R * T / F = 0.05916 V)', () => {
    const rGas = 8.31446 // J / (mol * K)
    const tempK = 298.15 // K (25 °C)
    const faraday = 96485.33 // C / mol
    const ln10 = Math.LN10 // ~ 2.302585

    // slopeFactor = (ln10 * R * T) / F
    const slopeFactor = (ln10 * rGas * tempK) / faraday // ~ 0.05916 V
    expect(slopeFactor).toBeCloseTo(0.05916, 5)
    expect(slopeFactor).toBeGreaterThan(0.059)
    expect(slopeFactor).toBeLessThan(0.060)
  })

  it('determines non-standard Daniell cell potential E under non-unit ion concentrations', () => {
    // Zn(s) + Cu^2+(aq) -> Zn^2+(aq) + Cu(s), n = 2, E° = 1.100 V
    const eStandard = 1.100 // V
    const nElectrons = 2
    const nernstFactor = 0.05916

    const concCu2Plus = 2.0 // M (high concentration in cathode)
    const concZn2Plus = 0.001 // M (dilute concentration in anode)

    // Reaction quotient Q = [Zn2+] / [Cu2+]
    const reactionQuotient = concZn2Plus / concCu2Plus // 5e-4
    expect(reactionQuotient).toBe(0.0005)

    // E = E° - (0.05916 / n) * log10(Q)
    const logQ = Math.log10(reactionQuotient) // ~ -3.30103
    const cellPotential = eStandard - (nernstFactor / nElectrons) * logQ // ~ 1.1976 V

    expect(cellPotential).toBeCloseTo(1.198, 3)
    expect(cellPotential).toBeGreaterThan(eStandard) // More positive due to Le Chatelier / Nernst push
  })

  it('verifies spontaneous voltage generated by an Ag+/Ag concentration cell', () => {
    // Both electrodes are pure Silver: E° = 0.000 V, n = 1
    // Anode: [Ag+]dilute = 0.005 M
    // Cathode: [Ag+]conc = 0.50 M
    const eStandard = 0.000 // V
    const nElectrons = 1
    const nernstFactor = 0.05916

    const concDilute = 0.005 // M
    const concConcentrated = 0.50 // M

    // Q = [Ag+]dilute / [Ag+]conc = 0.005 / 0.50 = 0.010 = 10^-2
    const qRatio = concDilute / concConcentrated
    expect(qRatio).toBe(0.01)

    // E = 0 - (0.05916 / 1) * log10(0.01) = -0.05916 * (-2) = +0.11832 V
    const concentrationCellPotential = eStandard - (nernstFactor / nElectrons) * Math.log10(qRatio)
    expect(concentrationCellPotential).toBeCloseTo(0.1183, 4)
    expect(concentrationCellPotential).toBeGreaterThan(0) // Spontaneous driving force
  })
})
