import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { ASPECT_DRILLS, CAPITAL_DRILLS, CAPITAL_TABLE, CHUNK_DRILLS, COLLOCATION_ROWS, FUNCTION_DRILLS, FUNCTION_TABLE, IF_DRILLS, NONFINITE_DRILLS, NONFINITE_TABLE, NOTE_FOLDERS, PATTERN_DRILLS, PATTERN_TABLE, POS_DRILLS, POS_TABLE, PREP_DRILLS, PREPOSITION_ROWS, PUNCT_DRILLS, PUNCTUATION_MARKS, SEMANTICS_DRILLS, SEMANTICS_TABLE, SOUND_DRILLS, SOUND_TABLE, STAGE_DRILLS, STUDY_STAGES, SYNTHESIS_SERIES, TENSE_DRILLS, TENSE_ROWS, TRANSITION_DRILLS, TRANSITION_TABLE } from './data/synthesisSeries'
import { translate } from '../i18n/messages'

describe('TOEIC synthesis series', () => {
  it('keeps eight teaching series and a tense grid without a score claim', () => {
    expect(SYNTHESIS_SERIES).toHaveLength(8)
    expect(SYNTHESIS_SERIES.map((item) => item.id)).toEqual([
      'pos',
      'syntax',
      'verbal',
      'mechanics',
      'lexicon',
      'sound',
      'semantics',
      'function',
    ])
    expect(TENSE_ROWS).toHaveLength(4)
    expect(TENSE_ROWS[0]?.cells).toHaveLength(4)
    expect(PREPOSITION_ROWS.map((row) => row.relation.en)).toEqual(['Time', 'Place', 'Direction', 'Abstract'])
    expect(PUNCTUATION_MARKS.length).toBeGreaterThanOrEqual(9)
    expect(STUDY_STAGES.length).toBeGreaterThanOrEqual(5)
    expect(STAGE_DRILLS).toHaveLength(6)
    expect(STAGE_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(STAGE_DRILLS.some((item) => item.why.en.includes('not a TOEIC score path'))).toBe(true)
    expect(NOTE_FOLDERS.some((row) => row.zh.includes('假分數'))).toBe(true)
    expect(COLLOCATION_ROWS.some((row) => row.chunk === 'make a decision')).toBe(true)
    expect(POS_TABLE.rows.length).toBeGreaterThanOrEqual(8)
    expect(POS_DRILLS).toHaveLength(8)
    expect(POS_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(POS_DRILLS.some((item) => item.why.en.includes('not a required formula'))).toBe(true)
    expect(PATTERN_TABLE.rows).toHaveLength(5)
    expect(NONFINITE_TABLE.rows).toHaveLength(3)
    expect(TRANSITION_TABLE.rows).toHaveLength(4)
    expect(SOUND_TABLE.rows).toHaveLength(5)
    expect(FUNCTION_TABLE.rows).toHaveLength(8)
    expect(FUNCTION_TABLE.rows.some((row) => row.cells[2].en.includes('not a company template'))).toBe(true)
    expect(SEMANTICS_TABLE.rows.map((row) => row.id)).toEqual(['syn', 'ant', 'homo', 'poly', 'homonym', 'meta'])
    expect(SEMANTICS_TABLE.rows.some((row) => row.cells[2].zh.includes('完全相同'))).toBe(true)
    expect(CAPITAL_TABLE.rows).toHaveLength(4)
    expect(CAPITAL_DRILLS).toHaveLength(8)
    expect(CAPITAL_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(CAPITAL_DRILLS.some((item) => item.why.en.includes('Not a company title rule'))).toBe(true)
    expect(PREP_DRILLS).toHaveLength(8)
    expect(PREP_DRILLS.map((item) => item.answer)).toEqual(['on', 'in', 'at', 'in', 'at', 'to', 'for', 'of'])
    expect(PREP_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(PUNCT_DRILLS).toHaveLength(8)
    expect(PUNCT_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(PUNCT_DRILLS.map((item) => item.id)).toEqual(['splice', 'its', 'its-is', 'indirect', 'hyphen', 'shout', 'colon', 'abbr'])
    expect(CHUNK_DRILLS).toHaveLength(8)
    expect(CHUNK_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(CHUNK_DRILLS.map((item) => item.answer)).toContain('make a decision')
    expect(CHUNK_DRILLS.map((item) => item.answer)).toContain('heavy rain')
    expect(PATTERN_DRILLS).toHaveLength(8)
    expect(PATTERN_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(new Set(PATTERN_DRILLS.map((item) => item.answer))).toEqual(new Set(['S+V', 'S+V+O', 'S+V+C', 'S+V+O+O', 'S+V+O+C']))
    expect(NONFINITE_DRILLS).toHaveLength(8)
    expect(NONFINITE_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(NONFINITE_DRILLS.some((item) => item.id === 'dangling' && item.answer.includes('After I left'))).toBe(true)
    expect(TRANSITION_DRILLS).toHaveLength(8)
    expect(TRANSITION_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(TRANSITION_DRILLS.some((item) => item.why.en.includes('not a comma splice'))).toBe(true)
    expect(FUNCTION_DRILLS).toHaveLength(8)
    expect(FUNCTION_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(FUNCTION_DRILLS.some((item) => item.why.en.includes('not a company template'))).toBe(true)
    expect(SOUND_DRILLS).toHaveLength(8)
    expect(SOUND_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(SOUND_DRILLS.some((item) => item.why.en.includes('Not a pronunciation certificate'))).toBe(true)
    expect(SEMANTICS_DRILLS).toHaveLength(8)
    expect(SEMANTICS_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(SEMANTICS_DRILLS.some((item) => item.why.zh.includes('完全相同'))).toBe(true)
    expect(TENSE_DRILLS).toHaveLength(8)
    expect(TENSE_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(TENSE_DRILLS.some((item) => item.id === 'yesterday' && item.answer === 'sent')).toBe(true)
    expect(IF_DRILLS).toHaveLength(8)
    expect(IF_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(IF_DRILLS.some((item) => item.id === 'would-have' && item.why.en.includes('not "contrary to fact"'))).toBe(true)
    expect(ASPECT_DRILLS).toHaveLength(8)
    expect(ASPECT_DRILLS.every((item) => item.choices.includes(item.answer))).toBe(true)
    expect(ASPECT_DRILLS.map((item) => item.answer)).toContain('has been writing')
    expect(ASPECT_DRILLS.map((item) => item.answer)).toContain('will have sent')
    expect(translate('zh-Hant', 'en.synthesis.prepDrillNote')).toMatch(/不計分/)
    expect(translate('en', 'en.synthesis.prepDrillNote')).toMatch(/not a score/)
    expect(translate('zh-Hant', 'en.synthesis.honesty')).toMatch(/不是多益分數/)
    expect(translate('en', 'en.synthesis.honesty')).toMatch(/Not a TOEIC score/)
    const view = readFileSync(join(process.cwd(), 'src/toeic/components/ToeicSynthesisSeries.tsx'), 'utf8')
    expect(view).toContain('scope="col"')
    expect(view).toContain('scope="row"')
    expect(view).toContain('stemId="prep-drill-stem"')
    expect(view).toContain('stemId="punct-drill-stem"')
    expect(view).toContain('stemId="chunk-drill-stem"')
    expect(view).toContain('stemId="pattern-drill-stem"')
    expect(view).toContain('stemId="nonfinite-drill-stem"')
    expect(view).toContain('stemId="transition-drill-stem"')
    expect(view).toContain('stemId="function-drill-stem"')
    expect(view).toContain('stemId="sound-drill-stem"')
    expect(view).toContain('stemId="semantics-drill-stem"')
    expect(view).toContain('stemId="tense-drill-stem"')
    expect(view).toContain('stemId="if-drill-stem"')
    expect(view).toContain('stemId="aspect-drill-stem"')
    expect(view).toContain('stemId="capital-drill-stem"')
    expect(view).toContain('stemId="pos-drill-stem"')
    expect(view).toContain('stemId="stage-drill-stem"')
    expect(view).toContain('aria-live="polite"')
    expect(view).toContain("t('en.synthesis.honesty')")
  })
})
